# Generated by Django 2.0.3 on 2018-06-03 18:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
