# Generated by Django 2.0.3 on 2018-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20180603_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='map_media',
            field=models.FileField(default=0, upload_to='medias'),
            preserve_default=False,
        ),
    ]
