# Generated by Django 2.0.3 on 2018-06-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180603_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='article',
            name='poster',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Affichiste'),
        ),
    ]
